# Generated by Django 5.0.2 on 2024-02-11 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mf_werk_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='org_file',
            field=models.FileField(blank=True, default='', upload_to='media/'),
        ),
    ]
