# Generated by Django 5.0.2 on 2024-02-22 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mf_werk_api', '0003_part_werk_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='werk_data',
        ),
        migrations.AddField(
            model_name='part',
            name='branded_file',
            field=models.FileField(blank=True, default='', upload_to='media/'),
        ),
        migrations.AddField(
            model_name='part',
            name='designation',
            field=models.CharField(default='', max_length=13600),
        ),
        migrations.AddField(
            model_name='part',
            name='drawing_id',
            field=models.CharField(default='', max_length=13600),
        ),
        migrations.AddField(
            model_name='part',
            name='general_tolerances',
            field=models.CharField(default='', max_length=13600),
        ),
        migrations.AddField(
            model_name='part',
            name='material',
            field=models.CharField(default='', max_length=13600),
        ),
        migrations.AddField(
            model_name='part',
            name='part_ids',
            field=models.CharField(default='', max_length=13600),
        ),
        migrations.AddField(
            model_name='part',
            name='weight',
            field=models.CharField(default='', max_length=13600),
        ),
    ]
