# Generated by Django 5.0.2 on 2024-02-22 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mf_werk_api', '0004_remove_part_werk_data_part_branded_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='designation',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='part',
            name='drawing_id',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='part',
            name='general_tolerances',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='part',
            name='material',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='part',
            name='part_ids',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='part',
            name='weight',
            field=models.JSONField(default=dict),
        ),
    ]
